'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const dlabel=d=>d?new Date(d+'T12:00:00').toLocaleDateString('es-US'):''
const sum=(a,k)=>a.reduce((s,x)=>s+Number(x[k]||0),0)
export default function AdvancedReports(){
 const [show,setShow]=useState(false),[workers,setWorkers]=useState([]),[methods,setMethods]=useState([]),[rows,setRows]=useState([]),[concepts,setConcepts]=useState([])
 const [worker,setWorker]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[status,setStatus]=useState(''),[method,setMethod]=useState(''),[min,setMin]=useState(''),[max,setMax]=useState('')
 useEffect(()=>{const check=()=>{const t=document.body?.innerText||'';setShow(t.includes('Informe de pagos')||t.includes('Informe de Pagos'))};check();const o=new MutationObserver(check);o.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>o.disconnect()},[])
 useEffect(()=>{if(!show)return;(async()=>{const [{data:w},{data:m}]=await Promise.all([sb.from('trabajadores').select('id,nombre').eq('activo',true).order('nombre'),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre')]);setWorkers(w||[]);setMethods(m||[])})()},[show])
 async function generate(){let q=sb.from('v_informe_liquidaciones_detallado').select('*').order('fecha_desde',{ascending:false});if(from)q=q.gte('fecha_hasta',from);if(to)q=q.lte('fecha_desde',to);if(worker)q=q.eq('trabajador_id',Number(worker));if(status)q=q.eq('estado',status);if(method==='none')q=q.is('metodo_pago_id',null);else if(method)q=q.eq('metodo_pago_id',Number(method));const {data,error}=await q;if(error)return alert('No fue posible generar el informe: '+error.message);let out=data||[];if(min!=='')out=out.filter(x=>Number(x.total_liquidado)>=Number(min));if(max!=='')out=out.filter(x=>Number(x.total_liquidado)<=Number(max));setRows(out);if(!out.length){setConcepts([]);return alert('No hay liquidaciones que coincidan con los filtros seleccionados.')}const ids=out.map(x=>x.id);const {data:ad}=await sb.from('ajustes_liquidacion').select('liquidacion_id,tipo,concepto,valor').in('liquidacion_id',ids);setConcepts(ad||[])}
 function clear(){setWorker('');setFrom('');setTo('');setStatus('');setMethod('');setMin('');setMax('');setRows([]);setConcepts([])}
 const totals=useMemo(()=>({hours:sum(rows,'total_horas'),hourValue:sum(rows,'valor_horas'),plus:sum(rows,'ajustes_suma'),minus:sum(rows,'ajustes_resta'),advances:sum(rows,'abonos'),otherMinus:sum(rows,'otras_restas'),liquidated:sum(rows,'total_liquidado'),paid:sum(rows,'total_pagado'),pending:sum(rows,'saldo_pendiente')}),[rows])
 const byWorker=useMemo(()=>Object.values(rows.reduce((a,x)=>{const k=x.trabajador||'Sin trabajador';if(!a[k])a[k]={name:k,hours:0,hourValue:0,plus:0,minus:0,liquidated:0,paid:0,pending:0};a[k].hours+=Number(x.total_horas||0);a[k].hourValue+=Number(x.valor_horas||0);a[k].plus+=Number(x.ajustes_suma||0);a[k].minus+=Number(x.ajustes_resta||0);a[k].liquidated+=Number(x.total_liquidado||0);a[k].paid+=Number(x.total_pagado||0);a[k].pending+=Number(x.saldo_pendiente||0);return a},{})),[rows])
 const byMethod=useMemo(()=>rows.reduce((a,x)=>{const k=x.forma_pago||'Sin forma de pago';a[k]=(a[k]||0)+Number(x.total_pagado||0);return a},{}),[rows])
 const byConcept=useMemo(()=>concepts.reduce((a,x)=>{const k=(x.concepto||'Sin concepto').trim();if(!a[k])a[k]={plus:0,minus:0};if(x.tipo==='suma')a[k].plus+=Number(x.valor||0);else a[k].minus+=Number(x.valor||0);return a},{}),[concepts])
 const filterText=[worker&&`Trabajador: ${workers.find(x=>String(x.id)===worker)?.nombre}`,from&&`Desde: ${dlabel(from)}`,to&&`Hasta: ${dlabel(to)}`,status&&`Estado: ${status}`,method&&`Pago: ${method==='none'?'Sin forma de pago':methods.find(x=>String(x.id)===method)?.nombre}`,min!==''&&`Mínimo: ${money(min)}`,max!==''&&`Máximo: ${money(max)}`].filter(Boolean).join(' · ')||'Todos los registros'
 if(!show)return null
 return <div style={{maxWidth:1200,margin:'14px auto 40px',padding:'0 4px'}}><section className="card advanced-reports"><h2>🔎 Informe pormenorizado de liquidaciones</h2><p>Separa horas, ajustes, abonos, pagos y saldos. Todos los totales se recalculan con los filtros.</p>
 <div className="grid no-print"><div className="field"><label>Trabajador</label><select value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Todos</option>{workers.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></div><div className="field"><label>Desde</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="field"><label>Hasta</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="field"><label>Estado</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{['pendiente','borrador','enviada','en_revision','devuelta','rechazada','aprobada','pagado','anulada'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Forma de pago</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Todas</option><option value="none">Sin forma de pago</option>{methods.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></div><div className="field"><label>Total mínimo</label><input type="number" value={min} onChange={e=>setMin(e.target.value)}/></div><div className="field"><label>Total máximo</label><input type="number" value={max} onChange={e=>setMax(e.target.value)}/></div></div>
 <div className="actions no-print"><button className="primary" onClick={generate}>Generar informe</button><button onClick={clear}>Limpiar</button>{rows.length>0&&<button onClick={()=>window.print()}>🖨️ Imprimir informe</button>}</div>
 {rows.length>0&&<div className="advanced-report-print"><h2>Informe pormenorizado de pagos</h2><p><b>Filtros:</b> {filterText}</p><div className="summary"><div className="stat">Liquidaciones<b>{rows.length}</b></div><div className="stat">Horas<b>{totals.hours.toFixed(2)}</b></div><div className="stat">Valor horas<b>{money(totals.hourValue)}</b></div><div className="stat">Ajustes (+)<b>{money(totals.plus)}</b></div><div className="stat">Ajustes (−)<b>{money(totals.minus)}</b></div><div className="stat">Abonos<b>{money(totals.advances)}</b></div><div className="stat">Otras restas<b>{money(totals.otherMinus)}</b></div><div className="stat">Total liquidado<b>{money(totals.liquidated)}</b></div><div className="stat">Pagado<b>{money(totals.paid)}</b></div><div className="stat">Pendiente<b>{money(totals.pending)}</b></div></div>
 <h3>Resumen por trabajador</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Trabajador</th><th>Horas</th><th>Valor horas</th><th>Ajustes +</th><th>Ajustes −</th><th>Total</th><th>Pagado</th><th>Pendiente</th></tr></thead><tbody>{byWorker.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.hours.toFixed(2)}</td><td>{money(x.hourValue)}</td><td>{money(x.plus)}</td><td>{money(x.minus)}</td><td>{money(x.liquidated)}</td><td>{money(x.paid)}</td><td>{money(x.pending)}</td></tr>)}</tbody></table></div>
 <h3>Detalle por liquidación</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Trabajador</th><th>Período</th><th>Horas</th><th>Valor horas</th><th>Ajustes +</th><th>Ajustes −</th><th>Abonos</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Estado</th><th>Pago</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.trabajador}</td><td>{dlabel(x.fecha_desde)} - {dlabel(x.fecha_hasta)}</td><td>{Number(x.total_horas||0).toFixed(2)}</td><td>{money(x.valor_horas)}</td><td>{money(x.ajustes_suma)}</td><td>{money(x.ajustes_resta)}</td><td>{money(x.abonos)}</td><td>{money(x.total_liquidado)}</td><td>{money(x.total_pagado)}</td><td>{money(x.saldo_pendiente)}</td><td>{x.estado}</td><td>{x.forma_pago||'-'}</td></tr>)}</tbody></table></div>
 <h3>Ajustes por concepto</h3>{Object.keys(byConcept).length?<div style={{overflowX:'auto'}}><table><thead><tr><th>Concepto</th><th>Sumas</th><th>Restas</th></tr></thead><tbody>{Object.entries(byConcept).map(([k,v])=><tr key={k}><td>{k}</td><td>{money(v.plus)}</td><td>{money(v.minus)}</td></tr>)}</tbody></table></div>:<p>Sin ajustes en el rango seleccionado.</p>}
 <h3>Pagado por forma de pago</h3><p>{Object.entries(byMethod).map(([k,v])=>`${k}: ${money(v)}`).join(' · ')||'Sin pagos registrados'}</p></div>}
 </section></div>
}
