'use client'
import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const today=()=>new Date().toLocaleDateString('en-CA')
export default function InlineLiquidationPayment(){
 const [host,setHost]=useState(null),[liq,setLiq]=useState(null),[payments,setPayments]=useState([]),[methods,setMethods]=useState([]),[value,setValue]=useState(''),[method,setMethod]=useState(''),[date,setDate]=useState(today())
 useEffect(()=>{let timer;const scan=()=>{const receipt=document.querySelector('.receipt-print');const h=receipt?.querySelector('h2');if(!receipt||h?.textContent?.trim()!=='Editar liquidación'){setHost(null);setLiq(null);return}let slot=receipt.querySelector('#inline-liquidation-payment');if(!slot){slot=document.createElement('div');slot.id='inline-liquidation-payment';slot.className='no-print';const actions=[...receipt.querySelectorAll('.actions.no-print')].pop();if(actions)receipt.insertBefore(slot,actions);else receipt.appendChild(slot)}setHost(slot);clearTimeout(timer);timer=setTimeout(resolveLiquidation,120)};const obs=new MutationObserver(scan);obs.observe(document.body,{childList:true,subtree:true});scan();return()=>{obs.disconnect();clearTimeout(timer)}},[])
 async function resolveLiquidation(){const receipt=document.querySelector('.receipt-print');if(!receipt)return;const dates=[...receipt.querySelectorAll('input[type=date]')].map(x=>x.value).filter(Boolean);const selects=[...receipt.querySelectorAll('select')];const workerSelect=selects.find(s=>s.querySelector('option[value=""]')?.textContent?.includes('Seleccionar'));const workerId=workerSelect?.value;if(!workerId||dates.length<2)return;const {data}=await sb.from('liquidaciones').select('id,trabajador_id,fecha_desde,fecha_hasta,gran_total,total_pago').eq('trabajador_id',Number(workerId)).eq('fecha_desde',dates[0]).eq('fecha_hasta',dates[1]).maybeSingle();if(data){setLiq(data);load(data.id)}}
 async function load(id){const [{data:p},{data:m}]=await Promise.all([sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',id).order('fecha'),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre')]);setPayments(p||[]);setMethods(m||[])}
 const paid=payments.reduce((s,p)=>s+Number(p.valor||0),0),caused=Number(liq?.gran_total??liq?.total_pago??0),balance=Math.max(caused-paid,0)
 async function save(){const v=Number(value);if(!liq)return;if(!v||v<=0)return alert('Escribe un valor de abono válido');if(v>balance+.001)return alert(`El abono no puede superar el saldo por pagar de ${money(balance)}`);const {error}=await sb.from('pagos_liquidacion').insert({liquidacion_id:liq.id,fecha:date,valor:v,metodo_pago_id:method?Number(method):null,concepto:'Pago / abono desde liquidación'});if(error)return alert(error.message);setValue('');await load(liq.id)}
 async function remove(id){if(!confirm('¿Eliminar este abono?'))return;const {error}=await sb.from('pagos_liquidacion').delete().eq('id',id);if(error)return alert(error.message);await load(liq.id)}
 if(!host||!liq)return null
 return createPortal(<div style={{marginTop:16,padding:14,border:'2px solid #d7e0ea',borderRadius:12}}><h3 style={{marginTop:0}}>💵 Pago / Abono</h3><p><b>Total causado:</b> {money(caused)} &nbsp; · &nbsp; <b>Total pagado:</b> {money(paid)} &nbsp; · &nbsp; <b>Saldo por pagar:</b> {money(balance)}</p><div className="grid"><div className="field"><label>Valor del abono</label><input type="number" min=".01" step=".01" value={value} onChange={e=>setValue(e.target.value)}/></div><div className="field"><label>Forma de pago</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Seleccionar...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></div><div className="field"><label>Fecha</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div className="actions"><button type="button" className="primary" onClick={save}>Registrar abono</button></div>{payments.length>0&&<div><h4>Abonos registrados</h4>{payments.map(p=><p key={p.id}>{p.fecha} — <b>{money(p.valor)}</b> — {p.metodos_pago?.nombre||'Sin especificar'} <button type="button" className="danger" onClick={()=>remove(p.id)}>Eliminar</button></p>)}</div>}</div>,host)
}
