'use client'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const today=()=>new Date().toLocaleDateString('en-CA')
const fresh=()=>({valor:'',metodo:'',fecha:today(),nota:''})
function screenTotal(){const r=document.querySelector('.receipt-print');const el=[...(r?.querySelectorAll('.total')||[])].find(x=>/GRAN TOTAL/i.test(x.textContent||''));const m=(el?.textContent||'').match(/\$\s*([\d,.]+)/);return m?Number(m[1].replace(/,/g,'')):null}
export default function InlineLiquidationPayment(){
 const [host,setHost]=useState(null),[liq,setLiq]=useState(null),[payments,setPayments]=useState([]),[methods,setMethods]=useState([]),[drafts,setDrafts]=useState([fresh()]),[saving,setSaving]=useState(false),[uiTotal,setUiTotal]=useState(null);const bypass=useRef(false),draftsRef=useRef(drafts),liqRef=useRef(liq);useEffect(()=>{draftsRef.current=drafts},[drafts]);useEffect(()=>{liqRef.current=liq},[liq])
 useEffect(()=>{let timer;const scan=()=>{const receipt=document.querySelector('.receipt-print');const h=receipt?.querySelector('h2');if(!receipt||h?.textContent?.trim()!=='Editar liquidación'){setHost(null);setLiq(null);return}const adjustTitle=[...receipt.querySelectorAll('h3')].find(x=>(x.textContent||'').trim()==='Ajustes adicionales');const adjustBox=adjustTitle?.parentElement;if(!adjustBox)return;let slot=adjustBox.querySelector('#inline-liquidation-payment');if(!slot){slot=document.createElement('div');slot.id='inline-liquidation-payment';slot.className='no-print';const grand=[...adjustBox.querySelectorAll('.total')].find(x=>/GRAN TOTAL/i.test(x.textContent||''));if(grand)adjustBox.insertBefore(slot,grand);else adjustBox.appendChild(slot)}setHost(slot);clearTimeout(timer);timer=setTimeout(resolveLiquidation,120)};const obs=new MutationObserver(scan);obs.observe(document.body,{childList:true,subtree:true,characterData:true});scan();return()=>{obs.disconnect();clearTimeout(timer)}},[])
 useEffect(()=>{if(!host)return;const sync=()=>{const n=screenTotal();if(n!==null)setUiTotal(n)};sync();const id=setInterval(sync,250);return()=>clearInterval(id)},[host])
 useEffect(()=>{const handler=async e=>{const b=e.target?.closest?.('button');if(!b||(b.textContent||'').trim().toLowerCase()!=='guardar cambios'||bypass.current)return;const pending=draftsRef.current.filter(d=>Number(d.valor)>0);if(!pending.length)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const current=liqRef.current;if(!current)return alert('No se identificó la liquidación para guardar los abonos.');for(const d of pending){if(!d.metodo)return alert('Selecciona la forma de pago de cada abono antes de Guardar cambios.')}setSaving(true);const rows=pending.map(d=>({liquidacion_id:current.id,fecha:d.fecha,valor:Number(d.valor),metodo_pago_id:Number(d.metodo),concepto:d.nota.trim()||'Abono'}));const {error}=await sb.from('pagos_liquidacion').insert(rows);setSaving(false);if(error)return alert('No se pudieron guardar los abonos: '+error.message);setDrafts([fresh()]);await load(current.id);bypass.current=true;b.click();setTimeout(()=>{bypass.current=false},500)};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[])
 async function resolveLiquidation(){const receipt=document.querySelector('.receipt-print');if(!receipt)return;const dates=[...receipt.querySelectorAll('input[type=date]')].map(x=>x.value).filter(Boolean);const selects=[...receipt.querySelectorAll('select')];const workerSelect=selects.find(s=>s.querySelector('option[value=""]')?.textContent?.includes('Seleccionar'));const workerId=workerSelect?.value;if(!workerId||dates.length<2)return;const {data}=await sb.from('liquidaciones').select('id,trabajador_id,fecha_desde,fecha_hasta,total_pago').eq('trabajador_id',Number(workerId)).eq('fecha_desde',dates[0]).eq('fecha_hasta',dates[1]).maybeSingle();if(data){setLiq(data);load(data.id)}}
 async function load(id){const [{data:p},{data:m}]=await Promise.all([sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',id).order('fecha'),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre')]);setPayments(p||[]);setMethods(m||[])}
 const paid=payments.reduce((s,p)=>s+Number(p.valor||0),0),caused=uiTotal??Number(liq?.total_pago??0),balance=Math.max(caused-paid,0)
 function change(i,k,v){setDrafts(drafts.map((d,j)=>j===i?{...d,[k]:v}:d))}
 async function save(i){const d=drafts[i],v=Number(d.valor);if(!liq)return;if(!v||v<=0)return alert('Escribe un valor de abono válido');if(!d.metodo)return alert('Selecciona la forma de pago');const currentTotal=screenTotal();const currentPaid=payments.reduce((s,p)=>s+Number(p.valor||0),0);if(currentTotal!==null&&v>Math.max(currentTotal-currentPaid,0)+.001)return alert(`El abono no puede superar el saldo ACTUAL de la liquidación: ${money(Math.max(currentTotal-currentPaid,0))}`);setSaving(true);const {error}=await sb.from('pagos_liquidacion').insert({liquidacion_id:liq.id,fecha:d.fecha,valor:v,metodo_pago_id:Number(d.metodo),concepto:d.nota.trim()||'Abono'});setSaving(false);if(error)return alert('No se pudo guardar el abono: '+error.message);setDrafts(drafts.map((x,j)=>j===i?fresh():x));await load(liq.id);alert('Abono guardado correctamente')}
 async function remove(id){if(!confirm('¿Eliminar este abono?'))return;const {error}=await sb.from('pagos_liquidacion').delete().eq('id',id);if(error)return alert(error.message);await load(liq.id)}
 if(!host||!liq)return null
 return createPortal(<div style={{marginTop:10}}><h3 style={{margin:'10px 0 8px'}}>💵 Abonos</h3>{payments.map(p=>{const note=p.concepto&&p.concepto!=='Abono'?` (${p.concepto})`:'';const method=p.metodos_pago?.nombre?` · ${p.metodos_pago.nombre}`:'';const line=`− Abono: ${money(p.valor)}${note}${method}`;return <div className="grid" key={p.id} data-print-payment={line} style={{marginBottom:8}}><div><b>− {money(p.valor)}</b></div><div>{p.metodos_pago?.nombre||'Sin especificar'}</div><div>{note}</div><div><button type="button" className="danger" onClick={()=>remove(p.id)}>Quitar</button></div></div>})}{drafts.map((d,i)=><div className="grid" key={'draft'+i} style={{marginBottom:8}}><div className="field"><input type="number" min=".01" step=".01" placeholder="Valor abono" value={d.valor} onChange={e=>change(i,'valor',e.target.value)}/></div><div className="field"><select value={d.metodo} onChange={e=>change(i,'metodo',e.target.value)}><option value="">Forma de pago...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></div><div className="field"><input placeholder="Nota aclaratoria" value={d.nota} onChange={e=>change(i,'nota',e.target.value)}/></div><div className="field"><input type="date" value={d.fecha} onChange={e=>change(i,'fecha',e.target.value)}/></div><div className="actions"><button type="button" className="primary" onClick={()=>save(i)} disabled={saving}>{saving?'Guardando...':'Guardar abono'}</button>{drafts.length>1&&<button type="button" onClick={()=>setDrafts(drafts.filter((_,j)=>j!==i))}>Quitar línea</button>}</div></div>)}<div className="actions"><button type="button" onClick={()=>setDrafts([...drafts,fresh()])}>+ Agregar otro abono</button></div><p><b>Total actual:</b> {money(caused)} &nbsp; · &nbsp; <b>Abonos reales registrados:</b> {money(paid)} &nbsp; · &nbsp; <b>Saldo actual:</b> {money(balance)}</p></div>,host)
}
