'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
export default function LiquidationPaymentBox(){
 const [visible,setVisible]=useState(false),[liq,setLiq]=useState(null),[payments,setPayments]=useState([]),[methods,setMethods]=useState([]),[value,setValue]=useState(''),[method,setMethod]=useState(''),[date,setDate]=useState(new Date().toLocaleDateString('en-CA'))
 useEffect(()=>{const detect=async()=>{const h=[...document.querySelectorAll('.receipt-print h2')].find(x=>/Editar liquidación/i.test(x.textContent||''));if(!h){setVisible(false);return}const worker=document.querySelector('.receipt-print select')?.value;const dates=[...document.querySelectorAll('.receipt-print input[type=date]')].map(x=>x.value);if(!worker||!dates[0]||!dates[1]){setVisible(false);return}const {data}=await sb.from('liquidaciones').select('id,gran_total,total_pago').eq('trabajador_id',Number(worker)).eq('fecha_desde',dates[0]).eq('fecha_hasta',dates[1]).maybeSingle();if(!data){setVisible(false);return}setLiq(data);setVisible(true);const [{data:p},{data:m}]=await Promise.all([sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',data.id).order('fecha'),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre')]);setPayments(p||[]);setMethods(m||[])};detect();const o=new MutationObserver(()=>{clearTimeout(window.__liqPayTimer);window.__liqPayTimer=setTimeout(detect,120)});o.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true});return()=>o.disconnect()},[])
 const paid=payments.reduce((s,p)=>s+Number(p.valor||0),0),caused=Number(liq?.gran_total??liq?.total_pago??0),balance=Math.max(caused-paid,0)
 async function save(){const v=Number(value);if(!v||v<=0)return alert('Escribe un valor de abono válido');if(v>balance+.001)return alert(`El abono no puede superar el saldo por pagar de ${money(balance)}`);const {error}=await sb.from('pagos_liquidacion').insert({liquidacion_id:liq.id,fecha:date,valor:v,metodo_pago_id:method?Number(method):null,concepto:'Abono desde liquidación'});if(error)return alert(error.message);setValue('');const {data}=await sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',liq.id).order('fecha');setPayments(data||[]);alert('Abono registrado correctamente')}
 async function remove(id){if(!confirm('¿Eliminar este abono?'))return;const {error}=await sb.from('pagos_liquidacion').delete().eq('id',id);if(error)return alert(error.message);setPayments(payments.filter(x=>x.id!==id))}
 if(!visible||!liq)return null
 return <div style={{maxWidth:1100,margin:'-8px auto 18px',padding:'0 4px'}}><section className="card no-print"><h3>💵 Pago / Abono de esta liquidación</h3><p>Total causado: <b>{money(caused)}</b> · Total pagado: <b>{money(paid)}</b> · Saldo por pagar: <b>{money(balance)}</b></p><div className="grid"><div className="field"><label>Valor del abono</label><input type="number" min=".01" step=".01" value={value} onChange={e=>setValue(e.target.value)}/></div><div className="field"><label>Forma de pago</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Seleccionar...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></div><div className="field"><label>Fecha</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div className="actions"><button className="primary" onClick={save} disabled={balance<=0}>💵 Registrar abono</button></div>{payments.length>0&&<div><h4>Abonos registrados</h4>{payments.map(p=><div className="worker-row" key={p.id}><span>{p.fecha} · <b>{money(p.valor)}</b> · {p.metodos_pago?.nombre||'Sin forma de pago'}</span><button className="danger" onClick={()=>remove(p.id)}>Eliminar</button></div>)}</div>}</section></div>
}
