'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const fresh=()=>({valor:'',metodo_pago_id:'',fecha:new Date().toLocaleDateString('en-CA'),nota:''})
export default function LiquidationPaymentBox(){
 const [visible,setVisible]=useState(false),[liq,setLiq]=useState(null),[payments,setPayments]=useState([]),[methods,setMethods]=useState([]),[drafts,setDrafts]=useState([fresh()])
 useEffect(()=>{const detect=async()=>{const h=[...document.querySelectorAll('.receipt-print h2')].find(x=>/Editar liquidación/i.test(x.textContent||''));if(!h){setVisible(false);return}const worker=document.querySelector('.receipt-print select')?.value;const dates=[...document.querySelectorAll('.receipt-print input[type=date]')].map(x=>x.value);if(!worker||!dates[0]||!dates[1]){setVisible(false);return}const {data}=await sb.from('liquidaciones').select('id,gran_total,total_pago').eq('trabajador_id',Number(worker)).eq('fecha_desde',dates[0]).eq('fecha_hasta',dates[1]).maybeSingle();if(!data){setVisible(false);return}setLiq(data);setVisible(true);const [{data:p},{data:m}]=await Promise.all([sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',data.id).order('fecha'),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre')]);setPayments(p||[]);setMethods(m||[])};detect();const o=new MutationObserver(()=>{clearTimeout(window.__liqPayTimer);window.__liqPayTimer=setTimeout(detect,120)});o.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true});return()=>o.disconnect()},[])
 const paid=payments.reduce((s,p)=>s+Number(p.valor||0),0),caused=Number(liq?.gran_total??liq?.total_pago??0),balance=Math.max(caused-paid,0)
 function change(i,k,v){setDrafts(drafts.map((x,j)=>j===i?{...x,[k]:v}:x))}
 async function save(i){const d=drafts[i],v=Number(d.valor);if(!v||v<=0)return alert('Escribe un valor de abono válido');if(!d.metodo_pago_id)return alert('Selecciona la forma de pago');if(v>balance+.001)return alert(`El abono no puede superar el saldo por pagar de ${money(balance)}`);const {error}=await sb.from('pagos_liquidacion').insert({liquidacion_id:liq.id,fecha:d.fecha,valor:v,metodo_pago_id:Number(d.metodo_pago_id),concepto:d.nota.trim()||'Abono'});if(error)return alert(error.message);const {data}=await sb.from('pagos_liquidacion').select('*,metodos_pago(nombre)').eq('liquidacion_id',liq.id).order('fecha');setPayments(data||[]);setDrafts(drafts.map((x,j)=>j===i?fresh():x));alert('Abono registrado correctamente')}
 async function remove(id){if(!confirm('¿Eliminar este abono?'))return;const {error}=await sb.from('pagos_liquidacion').delete().eq('id',id);if(error)return alert(error.message);setPayments(payments.filter(x=>x.id!==id))}
 if(!visible||!liq)return null
 return <div className="liq-pay-inline no-print"><h3>💵 Abonos</h3><p>Total causado: <b>{money(caused)}</b> · Abonado: <b>{money(paid)}</b> · Saldo por pagar: <b>{money(balance)}</b></p>{payments.map(p=><div className="grid" key={p.id} style={{marginBottom:8}}><div><b>💵 − {money(p.valor)}</b></div><div>{p.metodos_pago?.nombre||'Sin forma de pago'}</div><div>{p.concepto&&p.concepto!=='Abono'?`(${p.concepto})`:''}</div><div><button className="danger" type="button" onClick={()=>remove(p.id)}>Quitar</button></div></div>)}{drafts.map((d,i)=><div className="grid" key={'d'+i} style={{marginBottom:8}}><div className="field"><input type="number" min=".01" step=".01" placeholder="Valor abono" value={d.valor} onChange={e=>change(i,'valor',e.target.value)}/></div><div className="field"><select value={d.metodo_pago_id} onChange={e=>change(i,'metodo_pago_id',e.target.value)}><option value="">Forma de pago...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></div><div className="field"><input placeholder="Nota aclaratoria" value={d.nota} onChange={e=>change(i,'nota',e.target.value)}/></div><div className="field"><input type="date" value={d.fecha} onChange={e=>change(i,'fecha',e.target.value)}/></div><div className="actions"><button className="primary" type="button" onClick={()=>save(i)} disabled={balance<=0}>Guardar abono</button>{drafts.length>1&&<button type="button" onClick={()=>setDrafts(drafts.filter((_,j)=>j!==i))}>Quitar línea</button>}</div></div>)}<div className="actions"><button type="button" onClick={()=>setDrafts([...drafts,fresh()])}>+ Agregar otro abono</button></div><div className="total">SALDO POR PAGAR: {money(balance)}</div></div>
}
