'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import './globals.css';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const iso=d=>{const x=new Date(d+'T12:00:00');return x.toLocaleDateString('es-US',{weekday:'short',month:'2-digit',day:'2-digit',year:'numeric'})};
export default function App(){
 const [view,setView]=useState('liquidar'),[workers,setWorkers]=useState([]),[history,setHistory]=useState([]),[name,setName]=useState(''),[rate,setRate]=useState(''),[wid,setWid]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[days,setDays]=useState([]),[selected,setSelected]=useState(null),[msg,setMsg]=useState('');
 const load=async()=>{let {data}=await supabase.from('trabajadores').select('*').eq('activo',true).order('nombre');setWorkers(data||[]);let {data:h}=await supabase.from('liquidaciones').select('*,trabajadores(nombre)').order('created_at',{ascending:false});setHistory(h||[])};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!from||!to||to<from){setDays([]);return}let a=new Date(from+'T12:00:00'),b=new Date(to+'T12:00:00'),arr=[];while(a<=b){arr.push({fecha:a.toISOString().slice(0,10),horas:0});a.setDate(a.getDate()+1)}setDays(arr)},[from,to]);
 const worker=workers.find(w=>String(w.id)===String(wid)); const currentRate=Number(worker?.valor_hora||0); const totalHours=useMemo(()=>days.reduce((s,d)=>s+Number(d.horas||0),0),[days]); const total=totalHours*currentRate;
 async function addWorker(){if(!name.trim()||Number(rate)<=0)return setMsg('Completa nombre y valor hora.');let {error}=await supabase.from('trabajadores').insert({nombre:name.trim(),valor_hora:Number(rate)});if(error)return setMsg(error.message);setName('');setRate('');setMsg('Trabajador guardado.');load()}
 async function save(){if(!worker||!from||!to||!days.length)return setMsg('Selecciona trabajador y rango de fechas.');let {data:l,error}=await supabase.from('liquidaciones').insert({trabajador_id:worker.id,fecha_desde:from,fecha_hasta:to,valor_hora:currentRate,total_horas:totalHours,total_pago:total}).select().single();if(error)return setMsg(error.message);let rows=days.map(d=>({liquidacion_id:l.id,fecha:d.fecha,horas:Number(d.horas||0),valor_hora:currentRate,valor_dia:Number(d.horas||0)*currentRate}));let {error:e}=await supabase.from('detalle_horas').insert(rows);if(e)return setMsg(e.message);setMsg('Liquidación guardada correctamente.');load()}
 async function openPay(h){let {data}=await supabase.from('detalle_horas').select('*').eq('liquidacion_id',h.id).order('fecha');setSelected({...h,detalle:data||[]});setView('comprobante')}
 return <main className="wrap"><header className="head"><h1>Liquidación de Pagos</h1><div>Control sencillo de pagos de personal por horas</div></header><nav className="nav no-print"><button onClick={()=>setView('liquidar')}>+ Nueva liquidación</button><button onClick={()=>setView('trabajadores')}>👥 Trabajadores</button><button onClick={()=>setView('historial')}>📋 Historial</button></nav>{msg&&<div className="card no-print">{msg}</div>}
 {view==='trabajadores'&&<section className="card"><h2>Trabajadores</h2><div className="grid"><div><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre completo"/></label></div><div><label>Valor por hora<input type="number" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} placeholder="18.00"/></label></div></div><div className="actions"><button className="primary" onClick={addWorker}>Guardar trabajador</button></div><table><thead><tr><th>Nombre</th><th className="num">Valor/hora</th></tr></thead><tbody>{workers.map(w=><tr key={w.id}><td>{w.nombre}</td><td className="num">{money(w.valor_hora)}</td></tr>)}</tbody></table></section>}
 {view==='liquidar'&&<section className="card"><h2>Nueva liquidación</h2><div className="grid"><label>Trabajador<select value={wid} onChange={e=>setWid(e.target.value)}><option value="">Seleccionar...</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select></label><label>Valor hora<input value={worker?money(currentRate):''} disabled/></label><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{days.length>0&&<><table><thead><tr><th>Fecha</th><th>Horas</th><th className="num">Valor día</th></tr></thead><tbody>{days.map((d,i)=><tr key={d.fecha}><td>{iso(d.fecha)}</td><td><input type="number" min="0" step="0.25" value={d.horas} onChange={e=>setDays(days.map((x,j)=>j===i?{...x,horas:e.target.value}:x))}/></td><td className="num">{money(Number(d.horas||0)*currentRate)}</td></tr>)}</tbody></table><p className="total">Total: {totalHours.toFixed(2)} h — {money(total)}</p><div className="actions"><button className="primary" onClick={save}>Guardar liquidación</button><button className="secondary" onClick={()=>window.print()}>Imprimir</button></div></>}</section>}
 {view==='historial'&&<section className="card"><h2>Historial de pagos</h2><table><thead><tr><th>Trabajador</th><th>Período</th><th className="num">Horas</th><th className="num">Pago</th><th></th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.trabajadores?.nombre}</td><td>{h.fecha_desde} a {h.fecha_hasta}</td><td className="num">{h.total_horas}</td><td className="num">{money(h.total_pago)}</td><td><button onClick={()=>openPay(h)}>Ver</button></td></tr>)}</tbody></table></section>}
 {view==='comprobante'&&selected&&<section className="card"><h2>COMPROBANTE DE PAGO</h2><p><b>Trabajador:</b> {selected.trabajadores?.nombre}<br/><b>Período:</b> {selected.fecha_desde} al {selected.fecha_hasta}<br/><b>Valor hora:</b> {money(selected.valor_hora)}</p><table><thead><tr><th>Fecha</th><th className="num">Horas</th><th className="num">Valor/hora</th><th className="num">Pago</th></tr></thead><tbody>{selected.detalle.map(d=><tr key={d.id}><td>{iso(d.fecha)}</td><td className="num">{d.horas}</td><td className="num">{money(d.valor_hora)}</td><td className="num">{money(d.valor_dia)}</td></tr>)}</tbody></table><p className="total">TOTAL A PAGAR: {money(selected.total_pago)}</p><div className="actions no-print"><button className="primary" onClick={()=>window.print()}>🖨️ Imprimir comprobante</button><button className="secondary" onClick={()=>setView('historial')}>Volver</button></div></section>}</main>
}
