'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const labelDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('es-US',{weekday:'long',month:'2-digit',day:'2-digit',year:'numeric'}).replace(/^./,c=>c.toUpperCase()):''
const dateDays=(a,b)=>{if(!a||!b)return[];let o=[],d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00');while(d<=e){o.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return o}
const today=()=>new Date().toISOString().slice(0,10)


function CreateWorkerAccess({workers,onCreate}){const [mail,setMail]=useState(''),[phone,setPhone]=useState(''),[w,setW]=useState(''),[p,setP]=useState('');const cleanPhone=phone.replace(/[^0-9+]/g,'');return <div className="grid"><div className="field"><label>Correo electrónico</label><input type="email" placeholder="empleado@correo.com" value={mail} onChange={x=>setMail(x.target.value)}/><small>Puede iniciar sesión con este correo.</small></div><div className="field"><label>Teléfono de EE. UU.</label><input type="tel" placeholder="+1 305 555 1234" value={phone} onChange={x=>setPhone(x.target.value)}/><small>Puede iniciar sesión con este teléfono. Correo y teléfono pertenecen al MISMO acceso.</small></div><div className="field"><label>Trabajador</label><select value={w} onChange={x=>setW(x.target.value)}><option value="">Seleccionar...</option>{workers.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></div><div className="field"><label>Contraseña inicial</label><input type="password" minLength={8} value={p} onChange={x=>setP(x.target.value)}/></div><div className="actions"><button className="primary" onClick={()=>{const email=mail.trim().toLowerCase();if((!email&&!cleanPhone)||!w||p.length<8)return alert('Completa correo y/o teléfono, trabajador y una contraseña de mínimo 8 caracteres');if(cleanPhone&&!/^\+1\d{10}$/.test(cleanPhone))return alert('El teléfono debe tener formato +1 seguido de 10 dígitos');onCreate({email:email||null,phone:cleanPhone||null,trabajador_id:w,password:p});setP('')}}>Crear acceso único</button></div></div>}

export default function Page(){
 const [tab,setTab]=useState('new'),[workers,setWorkers]=useState([]),[history,setHistory]=useState([]),[methods,setMethods]=useState([])
 const [worker,setWorker]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[rows,setRows]=useState([]),[rate,setRate]=useState(''),[dailyRate,setDailyRate]=useState('')
 const [obs,setObs]=useState(''),[status,setStatus]=useState('pendiente'),[method,setMethod]=useState(''),[editId,setEditId]=useState(null),[adjustments,setAdjustments]=useState([])
 const [name,setName]=useState(''),[rateType,setRateType]=useState('hora'),[newRate,setNewRate]=useState(''),[editWorkerId,setEditWorkerId]=useState(null)
 const [methodName,setMethodName]=useState(''),[filter,setFilter]=useState('')
 const [rFrom,setRFrom]=useState(today()),[rTo,setRTo]=useState(today()),[report,setReport]=useState([])
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[authReady,setAuthReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[reviewNote,setReviewNote]=useState('')
 const [recoveryMode,setRecoveryMode]=useState(false),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[resetCode,setResetCode]=useState(''),[bootstrapMode,setBootstrapMode]=useState(false)
 const [accessUsers,setAccessUsers]=useState([]),[accessWorker,setAccessWorker]=useState('')
 const isAdmin=profile?.rol==='administrador',isWorker=profile?.rol==='trabajador'
 useEffect(()=>{let mounted=true;sb.auth.getSession().then(({data})=>{if(mounted){setSession(data.session);setAuthReady(true)}});const {data:{subscription}}=sb.auth.onAuthStateChange((e,s)=>{if(e==='PASSWORD_RECOVERY')setRecoveryMode(true);setSession(s);setProfile(null);setAuthReady(true)});return()=>{mounted=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session?.user)loadProfile();else setProfile(null)},[session?.user?.id])
 useEffect(()=>{if(profile){loadAll();if(isWorker)setTab('new')}},[profile?.user_id])
 useEffect(()=>{if(!profile)return;const ch=sb.channel('liquidaciones-live').on('postgres_changes',{event:'*',schema:'public',table:'liquidaciones'},()=>{loadHistory()}).subscribe();return()=>{sb.removeChannel(ch)}},[profile?.user_id])
 async function loadProfile(){let {data,error}=await sb.from('usuarios_app').select('*').eq('user_id',session.user.id).maybeSingle();if(error){alert(error.message);return}setProfile(data||{user_id:session.user.id,rol:'sin_acceso',activo:false})}
 async function login(e){e?.preventDefault();const id=email.trim();const credentials=id.startsWith('+')?{phone:id.replace(/[^0-9+]/g,''),password}:{email:id,password};let {error}=await sb.auth.signInWithPassword(credentials);if(error)return alert('No fue posible iniciar sesión: '+error.message);setPassword('')}
 async function bootstrapReset(e){e?.preventDefault();if(newPassword.length<8)return alert('La contraseña debe tener al menos 8 caracteres');if(newPassword!==confirmPassword)return alert('Las contraseñas no coinciden');let r=await fetch('/api/bootstrap-reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.trim(),password:newPassword,code:resetCode})});let j=await r.json();if(!r.ok)return alert(j.error||'No fue posible restablecer la contraseña');setPassword('');setNewPassword('');setConfirmPassword('');setResetCode('');setBootstrapMode(false);alert('Contraseña de administrador actualizada. Ya puedes iniciar sesión.')}
 async function adminApi(body){const {data}=await sb.auth.getSession();let r=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+data.session.access_token},body:JSON.stringify(body)});let j=await r.json();if(!r.ok)throw new Error(j.error||'Error administrativo');return j}
 async function logout(){await sb.auth.signOut();reset();setHistory([]);setWorkers([]);setMethods([])}
 async function saveNewPassword(e){e?.preventDefault();if(newPassword.length<8)return alert('La contraseña debe tener al menos 8 caracteres');if(newPassword!==confirmPassword)return alert('Las contraseñas no coinciden');let {error}=await sb.auth.updateUser({password:newPassword});if(error)return alert('No fue posible cambiar la contraseña: '+error.message);setNewPassword('');setConfirmPassword('');setRecoveryMode(false);alert('Contraseña actualizada correctamente. Ya puedes usar esta nueva contraseña para iniciar sesión.')}
 async function loadAll(){await Promise.all([loadWorkers(),loadHistory(),loadMethods(),...(isAdmin?[loadAccessUsers()]:[])])}
 async function loadAccessUsers(){let {data,error}=await sb.from('usuarios_app').select('*').order('created_at',{ascending:false});if(error)return;setAccessUsers(data||[])}
 async function linkAccess(u,workerId){if(!isAdmin)return;let id=workerId?Number(workerId):null;if(!id)return alert('Selecciona primero el trabajador');const w=workers.find(x=>String(x.id)===String(id));const dest=u.email||u.telefono||'este usuario';if(!confirm(`Vas a vincular y activar ${dest} EXCLUSIVAMENTE para ${w?.nombre||'este trabajador'}. Si ${w?.nombre||'el trabajador'} tenía otro acceso, quedará desvinculado para evitar errores. ¿Continuar?`))return;const other=accessUsers.find(x=>x.user_id!==u.user_id&&String(x.trabajador_id)===String(id));if(other){let {error:e1}=await sb.from('usuarios_app').update({trabajador_id:null,activo:false}).eq('user_id',other.user_id);if(e1)return alert(e1.message)}let {error}=await sb.from('usuarios_app').update({trabajador_id:id,rol:'trabajador',activo:true}).eq('user_id',u.user_id);if(error)return alert(error.message);await loadAccessUsers();alert(`Acceso de ${w?.nombre||'trabajador'} vinculado y activado correctamente`)}
 async function disableAccess(u){if(!confirm(`¿Desactivar el acceso de ${u.email||'este usuario'}?`))return;let {error}=await sb.from('usuarios_app').update({activo:false}).eq('user_id',u.user_id);if(error)return alert(error.message);await loadAccessUsers()}
 async function accessMessage(u,medio){const w=workers.find(x=>String(x.id)===String(u.trabajador_id));if(!w)throw new Error('Este acceso todavía no está vinculado a un trabajador');const login=medio==='telefono'?u.telefono:u.email;return {w,text:`Hola ${w.nombre}. Este es tu acceso personal a Liquidación de Pagos:
https://liquidacion-pagos.vercel.app
Usuario: ${login}
También puedes iniciar sesión con ${medio==='telefono'?(u.email||'tu correo registrado'):(u.telefono||'tu teléfono registrado')}.
Usa la contraseña temporal entregada por el administrador. En tu primer ingreso la aplicación te pedirá crear tu contraseña personal. Este acceso está vinculado únicamente a tu liquidación.`}}
 async function markAccessSent(u){await sb.from('usuarios_app').update({acceso_enviado_at:new Date().toISOString()}).eq('user_id',u.user_id);await loadAccessUsers()}
 async function sendWorkerWhatsApp(u){try{const {w,text}=await accessMessage(u,'telefono');if(!u.telefono)return alert('Este acceso no tiene un teléfono registrado');const phone=String(u.telefono).replace(/\D/g,'');const masked=phone.length>=4?'••••'+phone.slice(-4):phone;if(!confirm(`Vas a abrir WhatsApp EXCLUSIVAMENTE para ${w.nombre}, teléfono terminado en ${masked}. ¿Continuar?`))return;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');await markAccessSent(u)}catch(e){alert('No fue posible preparar WhatsApp: '+e.message)}}
 async function sendWorkerGmail(u){try{const {w,text}=await accessMessage(u,'email');if(!u.email)return alert('Este acceso no tiene un correo registrado');const masked=u.email.replace(/(^.).*(@.*$)/,'$1••••$2');if(!confirm(`Vas a abrir Gmail con el mensaje dirigido EXCLUSIVAMENTE a ${w.nombre} (${masked}). ¿Continuar?`))return;const url=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(u.email)}&su=${encodeURIComponent('Acceso a Liquidación de Pagos')}&body=${encodeURIComponent(text)}`;window.open(url,'_blank','noopener,noreferrer');await markAccessSent(u)}catch(e){alert('No fue posible preparar Gmail: '+e.message)}}
 async function resetWorkerPassword(u){const w=workers.find(x=>String(x.id)===String(u.trabajador_id));if(!w)return alert('Primero vincula este acceso a un trabajador');const p=prompt(`Escribe una NUEVA CONTRASEÑA TEMPORAL para ${w.nombre} (mínimo 8 caracteres). El trabajador tendrá que cambiarla al ingresar.`);if(p===null)return;if(p.length<8)return alert('La contraseña temporal debe tener al menos 8 caracteres');try{await adminApi({action:'password',user_id:u.user_id,password:p});await loadAccessUsers();alert('Contraseña temporal actualizada. Ahora puedes compartir el acceso por WhatsApp o Gmail, según los datos registrados del trabajador.')}catch(e){alert(e.message)}}
 async function changeOwnPassword(){if(newPassword.length<8)return alert('La contraseña debe tener al menos 8 caracteres');if(newPassword!==confirmPassword)return alert('Las contraseñas no coinciden');let {error}=await sb.auth.updateUser({password:newPassword});if(error)return alert(error.message);if(profile?.requiere_cambio_clave){let {error:ce}=await sb.rpc('completar_cambio_clave');if(ce)return alert('La contraseña cambió, pero no se pudo completar el primer acceso: '+ce.message);setProfile({...profile,requiere_cambio_clave:false})}setNewPassword('');setConfirmPassword('');alert('Contraseña actualizada correctamente')}
 async function loadWorkers(){let q=sb.from('trabajadores').select('*').eq('activo',true).order('nombre');if(isWorker&&profile?.trabajador_id)q=q.eq('id',profile.trabajador_id);let {data}=await q;setWorkers(data||[]);if(isWorker&&data?.[0])chooseWorker(String(data[0].id))}
 async function loadHistory(){let q=sb.from('liquidaciones').select('*, trabajadores(nombre), metodos_pago(nombre)').order('created_at',{ascending:false});if(isWorker&&profile?.trabajador_id)q=q.eq('trabajador_id',Number(profile.trabajador_id));let {data,error}=await q;if(error){console.error(error);return}setHistory(data||[])}
 async function loadMethods(){let {data}=await sb.from('metodos_pago').select('*').eq('activo',true).order('nombre');setMethods(data||[])}
 function makeRows(a,b,old={}){setRows(dateDays(a,b).map(fecha=>({fecha,horas:old[fecha]??''})))}
 function chooseWorker(id){setWorker(id);let w=workers.find(x=>String(x.id)===String(id));const h=w?.valor_hora||'';setRate(h);setDailyRate(w?.valor_dia|| (h?Number(h)*8:''))}
 function changeHourly(v){setRate(v);setDailyRate(v===''?'':(Number(v)*8).toFixed(2))}
 function changeDaily(v){setDailyRate(v);setRate(v===''?'':(Number(v)/8).toFixed(2))}
 const totalHours=useMemo(()=>rows.reduce((s,r)=>s+Number(r.horas||0),0),[rows]),total=totalHours*Number(rate||0)
 const adjustmentsNet=adjustments.reduce((n,a)=>n+(a.tipo==='suma'?1:-1)*Number(a.valor||0),0),grandTotal=total+adjustmentsNet
 async function addWorker(){
  if(!name.trim()||!newRate)return alert('Completa nombre y tarifa')
  let hourly=rateType==='dia'?Number(newRate)/8:Number(newRate),daily=rateType==='dia'?Number(newRate):Number(newRate)*8
  let payload={nombre:name.trim(),valor_hora:hourly,valor_dia:daily,tipo_tarifa:rateType,activo:true}
  let q=editWorkerId?sb.from('trabajadores').update(payload).eq('id',editWorkerId):sb.from('trabajadores').insert(payload)
  let {error}=await q;if(error)return alert(error.message)
  setName('');setNewRate('');setRateType('hora');setEditWorkerId(null);await loadWorkers();alert(editWorkerId?'Trabajador actualizado':'Trabajador guardado')
 }
 function startEditWorker(w){setName(w.nombre);setRateType(w.tipo_tarifa||'hora');setNewRate(String((w.tipo_tarifa||'hora')==='dia'?(w.valor_dia??Number(w.valor_hora)*8):w.valor_hora));setEditWorkerId(w.id);window.scrollTo({top:0,behavior:'smooth'})}
 async function unlinkWorker(w){if(!isAdmin)return;const u=accessUsers.find(x=>String(x.trabajador_id)===String(w.id));if(!u)return alert('Este trabajador no tiene un acceso vinculado');if(!confirm(`¿Desvincular el acceso de ${w.nombre}?\n\nSe conserva el trabajador y todo su historial, pero la cuenta dejará de acceder a sus liquidaciones.`))return;let {error}=await sb.from('usuarios_app').update({trabajador_id:null,activo:false}).eq('user_id',u.user_id);if(error)return alert(error.message);await Promise.all([loadAccessUsers(),loadWorkers()]);alert('Acceso desvinculado correctamente')}
 async function deleteWorker(w){if(!isAdmin)return;if(!confirm(`¿ANULAR a ${w.nombre}?\n\nNo aparecerá en nuevas liquidaciones y su acceso quedará desactivado. El historial se conservará.`))return;if(!confirm(`SEGUNDA CONFIRMACIÓN: ¿Realmente deseas anular a ${w.nombre}?`))return;let {error}=await sb.from('trabajadores').update({activo:false}).eq('id',w.id);if(error)return alert(error.message);let {error:ue}=await sb.from('usuarios_app').update({activo:false,trabajador_id:null}).eq('trabajador_id',w.id);if(ue)return alert(ue.message);if(String(worker)===String(w.id))setWorker('');await Promise.all([loadWorkers(),loadAccessUsers()]);alert('Trabajador anulado. Su historial se conserva.')}
 async function findOverlap(){if(!worker||!from||!to)return null;let q=sb.from('liquidaciones').select('*, trabajadores(nombre), metodos_pago(nombre)').eq('trabajador_id',Number(worker)).not('estado','in','(anulada,rechazada)').lte('fecha_desde',to).gte('fecha_hasta',from).order('fecha_desde').limit(1);if(editId)q=q.neq('id',editId);let {data,error}=await q;if(error)throw error;return data?.[0]||null}
 async function newFromRejected(p){
  if(!isWorker||String(p.trabajador_id)!==String(profile?.trabajador_id))return alert('Solo el trabajador puede crear nuevamente esta liquidación')
  if(p.estado!=='rechazada')return alert('Esta liquidación no está rechazada')
  reset();setWorker(String(profile.trabajador_id));setFrom(p.fecha_desde);setTo(p.fecha_hasta);setRate(p.valor_hora||'');setDailyRate(p.valor_dia??Number(p.valor_hora||0)*8);setObs('');makeRows(p.fecha_desde,p.fecha_hasta,{});setTab('new')
  setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),50)
 }
 async function annulPay(p){if(isWorker&&String(p.trabajador_id)!==String(profile?.trabajador_id))return alert('No tienes permiso para anular esta liquidación');if(isWorker&&!['borrador','devuelta','pendiente'].includes(p.estado))return alert('Esta liquidación debe ser anulada por el administrador');if(!confirm(`¿Anular la liquidación del período ${p.fecha_desde} a ${p.fecha_hasta}?\n\nSe conservará en el historial, pero dejará libre el período.`))return;let payload={estado:'anulada'};if(isAdmin){payload.revisado_at=new Date().toISOString();payload.revisado_por=session.user.id}let {error}=await sb.from('liquidaciones').update(payload).eq('id',p.id);if(error)return alert(error.message);await sb.from('liquidacion_auditoria').insert({liquidacion_id:p.id,actor_id:session.user.id,accion:'anulada',estado_anterior:p.estado,estado_nuevo:'anulada',total_anterior:p.gran_total??p.total_pago,nota:'Liquidación anulada'});await loadHistory();alert('Liquidación anulada. El período quedó disponible.')}
 async function addMethod(){if(!methodName.trim())return;let {error}=await sb.from('metodos_pago').insert({nombre:methodName.trim()});if(error)return alert(error.message);setMethodName('');loadMethods()}
 async function save(mode='admin'){
  if(!worker||!from||!to||!rate)return alert('Completa trabajador, fechas y tarifa')
  if(isWorker&&String(worker)!==String(profile?.trabajador_id))return alert('Solo puedes crear tu propia liquidación')
  if(isAdmin&&status==='pagado'&&!method)return alert('Selecciona de dónde se pagó')
  let overlap;try{overlap=await findOverlap()}catch(e){return alert('No fue posible verificar el período: '+e.message)}if(overlap){if(isWorker&&['borrador','devuelta','pendiente'].includes(overlap.estado)){if(confirm(`Ya existe una liquidación que se cruza con este período (${overlap.fecha_desde} a ${overlap.fecha_hasta}). ¿Abrirla para corregirla?`))await editPay(overlap);return}return alert(`Ya existe una liquidación que se cruza con este período (${overlap.fecha_desde} a ${overlap.fecha_hasta}) con estado ${overlap.estado}. Debe corregirse o anularse antes de continuar.`)}
  let payload={trabajador_id:Number(worker),fecha_desde:from,fecha_hasta:to,valor_hora:Number(rate),valor_dia:Number(dailyRate||Number(rate)*8),total_horas:totalHours,total_pago:total,observaciones:obs||null,estado:isWorker?'borrador':status,metodo_pago_id:isAdmin&&status==='pagado'?Number(method):null,gran_total:grandTotal}
  let id=editId
  if(id){let {error}=await sb.from('liquidaciones').update(payload).eq('id',id);if(error)return alert(error.message);await sb.from('detalle_horas').delete().eq('liquidacion_id',id)}
  else{let {data,error}=await sb.from('liquidaciones').insert(payload).select('id').single();if(error){if(error.code==='23505'&&isWorker){const {data:existing}=await sb.from('liquidaciones').select('*, trabajadores(nombre), metodos_pago(nombre)').eq('trabajador_id',Number(worker)).eq('fecha_desde',from).eq('fecha_hasta',to).maybeSingle();if(existing){if(['borrador','devuelta'].includes(existing.estado)){alert('Ya existe una liquidación para esta semana. Abriremos la existente para continuarla.');await editPay(existing)}else{alert(existing.estado==='aprobada'?'Esta semana ya está aprobada y solo puede consultarse.':'Esta semana ya fue enviada y está esperando revisión del administrador.');setTab('history')}return}}return alert(error.message)}id=data.id}
  let det=rows.filter(r=>Number(r.horas)>0).map(r=>({liquidacion_id:id,fecha:r.fecha,horas:Number(r.horas),valor_hora:Number(rate),valor_dia:Number(r.horas)*Number(rate)}))
  if(det.length){let {error}=await sb.from('detalle_horas').insert(det);if(error)return alert(error.message)}
  if(editId) await sb.from('ajustes_liquidacion').delete().eq('liquidacion_id',id)
  const adj=adjustments.filter(a=>a.concepto.trim()&&Number(a.valor)>=0).map(a=>({liquidacion_id:id,tipo:a.tipo,concepto:a.concepto.trim(),valor:Number(a.valor)}))
  if(adj.length){let {error}=await sb.from('ajustes_liquidacion').insert(adj);if(error)return alert(error.message)}
  if(isWorker&&mode==='send'){let {error}=await sb.from('liquidaciones').update({estado:'enviada',enviado_at:new Date().toISOString(),total_enviado_trabajador:grandTotal}).eq('id',id);if(error)return alert(error.message);await sb.from('liquidacion_auditoria').insert({liquidacion_id:id,actor_id:session.user.id,accion:'enviada',estado_anterior:'borrador',estado_nuevo:'enviada',total_nuevo:grandTotal})}
  reset();await loadHistory();setTab(isWorker?'history':'history');alert(isWorker?(mode==='send'?'Liquidación enviada al administrador':'Borrador guardado'):'Liquidación guardada')
 }
 function reset(){setWorker('');setFrom('');setTo('');setRows([]);setRate('');setDailyRate('');setObs('');setStatus('pendiente');setMethod('');setEditId(null);setAdjustments([])}
 async function editPay(p){if(isWorker&&String(p.trabajador_id)!==String(profile?.trabajador_id))return alert('No tienes permiso para abrir esta liquidación');let {data}=await sb.from('detalle_horas').select('*').eq('liquidacion_id',p.id);let {data:ad}=await sb.from('ajustes_liquidacion').select('*').eq('liquidacion_id',p.id).order('id');setAdjustments((ad||[]).map(a=>({tipo:a.tipo,concepto:a.concepto,valor:a.valor})));let old={};(data||[]).forEach(x=>old[x.fecha]=x.horas);setEditId(p.id);setWorker(String(p.trabajador_id));setRate(p.valor_hora);setDailyRate(p.valor_dia??Number(p.valor_hora||0)*8);setFrom(p.fecha_desde);setTo(p.fecha_hasta);setObs(p.observaciones||'');setStatus(p.estado||'pendiente');setMethod(p.metodo_pago_id?String(p.metodo_pago_id):'');makeRows(p.fecha_desde,p.fecha_hasta,old);setTab('new')}

 async function reviewPay(p,next){
  if(!isAdmin)return
  const labels={aprobada:'aprobar',devuelta:'devolver',rechazada:'rechazar',en_revision:'marcar en revisión'}
  if(!confirm(`¿Confirmas ${labels[next]||next} esta liquidación?`))return
  const payload={estado:next,revisado_at:new Date().toISOString(),revisado_por:session.user.id,comentario_admin:reviewNote||null}
  if(next==='aprobada')payload.total_final_admin=Number(p.gran_total??p.total_pago)
  let {error}=await sb.from('liquidaciones').update(payload).eq('id',p.id);if(error)return alert(error.message)
  await sb.from('liquidacion_auditoria').insert({liquidacion_id:p.id,actor_id:session.user.id,accion:next,estado_anterior:p.estado,estado_nuevo:next,total_anterior:p.total_enviado_trabajador??p.gran_total,total_nuevo:p.gran_total,nota:reviewNote||null})
  setReviewNote('');await loadHistory()
 }
 async function delPay(p){if(!confirm('¿Eliminar esta liquidación?'))return;let {error}=await sb.from('liquidaciones').delete().eq('id',p.id);if(error)return alert(error.message);loadHistory()}
 async function printPay(p){let {data}=await sb.from('detalle_horas').select('*').eq('liquidacion_id',p.id).order('fecha');let {data:ad}=await sb.from('ajustes_liquidacion').select('*').eq('liquidacion_id',p.id).order('id');setAdjustments((ad||[]).map(a=>({tipo:a.tipo,concepto:a.concepto,valor:a.valor})));setWorker(String(p.trabajador_id));setRate(p.valor_hora);setDailyRate(p.valor_dia??Number(p.valor_hora||0)*8);setFrom(p.fecha_desde);setTo(p.fecha_hasta);setObs(p.observaciones||'');setStatus(p.estado||'pendiente');setMethod(p.metodo_pago_id?String(p.metodo_pago_id):'');setRows((data||[]).map(x=>({fecha:x.fecha,horas:x.horas})));setTab('new');setTimeout(()=>window.print(),200)}
 async function runReport(a=rFrom,b=rTo){if(!a||!b)return alert('Selecciona el rango');let {data,error}=await sb.from('liquidaciones').select('*, trabajadores(nombre), metodos_pago(nombre)').lte('fecha_desde',b).gte('fecha_hasta',a).order('fecha_desde');if(error)return alert(error.message);setReport(data||[])}
 const reportHours=report.reduce((s,p)=>s+Number(p.total_horas||0),0),reportTotal=report.reduce((s,p)=>s+Number((p.gran_total??p.total_pago)||0),0)
 const paidTotal=report.filter(p=>p.estado==='pagado').reduce((s,p)=>s+Number((p.gran_total??p.total_pago)||0),0)
 const byMethod=report.filter(p=>p.estado==='pagado').reduce((a,p)=>{let k=p.metodos_pago?.nombre||'Sin especificar';a[k]=(a[k]||0)+Number((p.gran_total??p.total_pago)||0);return a},{})
 const filtered=history.filter(h=>!filter||String(h.trabajador_id)===filter)
 const pendingReview=history.filter(h=>['enviada','en_revision'].includes(h.estado)).length
 if(recoveryMode&&session)return <main><header className="hero"><h1>Liquidación de Pagos</h1><p>Recuperación de acceso</p></header><section className="card login-card"><h2>Crear nueva contraseña</h2><p>Escribe una contraseña nueva para tu cuenta.</p><form onSubmit={saveNewPassword}><div className="field"><label>Nueva contraseña</label><input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></div><div className="field"><label>Confirmar contraseña</label><input type="password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></div><div className="actions"><button className="primary" type="submit">Guardar nueva contraseña</button></div></form></section></main>
  if(!authReady)return <main><section className="card login-card"><h2>Cargando…</h2></section></main>
 if(!session)return <main><header className="hero"><h1>Liquidación de Pagos</h1><p>Acceso seguro</p></header><section className="card login-card"><h2>{bootstrapMode?'Restablecer acceso administrador':'Iniciar sesión'}</h2>{bootstrapMode?<form onSubmit={bootstrapReset}><div className="field"><label>Correo del administrador</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Código administrativo</label><input type="password" value={resetCode} onChange={e=>setResetCode(e.target.value)} required/></div><div className="field"><label>Nueva contraseña</label><input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></div><div className="field"><label>Confirmar contraseña</label><input type="password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></div><div className="actions"><button className="primary" type="submit">Guardar nueva contraseña</button><button type="button" onClick={()=>setBootstrapMode(false)}>Volver</button></div></form>:<form onSubmit={login}><div className="field"><label>Correo o teléfono</label><input type="text" placeholder="correo@ejemplo.com o +1..." value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Contraseña</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="actions"><button className="primary" type="submit">Entrar</button></div><button className="link-button" type="button" onClick={()=>setBootstrapMode(true)}>Restablecer acceso de administrador</button></form>}</section></main>
 if(!profile?.activo)return <main><section className="card login-card"><h2>Cuenta sin acceso</h2><p>Tu cuenta existe, pero el administrador todavía no la ha vinculado a un trabajador.</p><button onClick={logout}>Cerrar sesión</button></section></main>
 if(isWorker&&profile?.requiere_cambio_clave)return <main><header className="hero"><h1>Liquidación de Pagos</h1><p>Primer ingreso</p></header><section className="card login-card"><h2>🔑 Crea tu contraseña personal</h2><p>La contraseña que recibiste es temporal. Antes de usar la aplicación debes crear una contraseña que solo tú conozcas.</p><div className="field"><label>Nueva contraseña</label><input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></div><div className="field"><label>Confirmar contraseña</label><input type="password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></div><div className="actions"><button className="primary" onClick={changeOwnPassword}>Guardar y entrar</button><button onClick={logout}>Cerrar sesión</button></div></section></main>
 return <main>
 <header className="hero"><div><h1>Liquidación de Pagos</h1><p>{isAdmin?'Panel administrador':`Portal del trabajador${workers[0]?.nombre?' · '+workers[0].nombre:''}`}</p></div><button className="logout no-print" onClick={logout}>Cerrar sesión</button></header>
 {isAdmin?<nav className="nav no-print"><button onClick={()=>{reset();setTab('new')}}>➕ Nueva liquidación</button><button onClick={()=>setTab('workers')}>👥 Trabajadores</button><button onClick={()=>{loadAccessUsers();setTab('access')}}>🔐 Accesos</button><button className={pendingReview>0?'primary':''} onClick={()=>setTab('received')}>📥 Liquidaciones recibidas {pendingReview>0&&<span className="notify">{pendingReview}</span>}</button><button onClick={()=>setTab('history')}>📋 Historial</button><button onClick={()=>setTab('reports')}>📊 Informes</button></nav>:<nav className="nav worker-nav no-print"><button onClick={()=>{reset();if(workers[0])chooseWorker(String(workers[0].id));setTab('new')}}>📝 Mi liquidación</button><button onClick={()=>setTab('history')}>📋 Mis liquidaciones</button></nav>}

 {isAdmin&&tab==='workers'&&<section className="card no-print"><h2>Trabajadores</h2><div className="grid">
 <div className="field"><label>Nombre</label><input value={name} onChange={e=>setName(e.target.value)}/></div>
 <div className="field"><label>Tipo de tarifa</label><select value={rateType} onChange={e=>setRateType(e.target.value)}><option value="hora">Valor hora</option><option value="dia">Valor día (8 horas)</option></select></div>
 <div className="field"><label>{rateType==='dia'?'Valor día':'Valor hora'}</label><input type="number" step=".01" value={newRate} onChange={e=>setNewRate(e.target.value)}/>{rateType==='dia'&&newRate&&<small>Valor hora automático: <b>{money(Number(newRate)/8)}</b></small>}</div></div>
 <div className="actions"><button className="primary" onClick={addWorker}>{editWorkerId?'Guardar cambios':'Guardar trabajador'}</button>{editWorkerId&&<button onClick={()=>{setEditWorkerId(null);setName('');setNewRate('');setRateType('hora')}}>Cancelar edición</button>}</div>
 <h3>Personal registrado</h3>{workers.map(w=><div key={w.id} className="worker-row"><div><b>{w.nombre}</b> — {money(w.valor_hora)}/h{w.valor_dia?<> — {money(w.valor_dia)}/día</>:null}</div><div className="actions"><button onClick={()=>startEditWorker(w)}>✏️ Editar</button><button onClick={()=>unlinkWorker(w)}>🔗 Desvincular acceso</button><button className="danger" onClick={()=>deleteWorker(w)}>🚫 Anular trabajador</button></div></div>)}
 <hr/><h3>Opciones de pago</h3><div className="grid"><div className="field"><label>Nueva opción</label><input placeholder="Ej. Chase, Bank of America..." value={methodName} onChange={e=>setMethodName(e.target.value)}/></div></div><div className="actions"><button onClick={addMethod}>+ Crear opción de pago</button></div><p>{methods.map(m=>m.nombre).join(' · ')}</p></section>}

 {isAdmin&&tab==='access'&&<section className="card no-print"><h2>🔐 Administrar accesos</h2><p>Los usuarios nuevos aparecen aquí. Vincula cada correo o teléfono con un trabajador para darle acceso únicamente a sus liquidaciones.</p>{accessUsers.filter(u=>u.rol!=='administrador').length===0?<p><b>No hay cuentas de trabajadores pendientes.</b></p>:accessUsers.filter(u=>u.rol!=='administrador').map(u=><div className="worker-row" key={u.user_id}><div><b>{workers.find(w=>String(w.id)===String(u.trabajador_id))?.nombre||'Sin trabajador vinculado'}</b><br/><span>{u.email||u.telefono||'Usuario sin correo/teléfono'}</span><br/><small>{u.activo?'Acceso activo':'Acceso pendiente/desactivado'}{u.requiere_cambio_clave?' · 🔑 Debe crear contraseña personal':''}{u.acceso_enviado_at?' · 📲 Acceso preparado/enviado':''}</small></div><AccessActions u={u} workers={workers} onActivate={linkAccess} onWhatsApp={sendWorkerWhatsApp} onGmail={sendWorkerGmail} onPassword={resetWorkerPassword} onDisable={disableAccess}/></div>)}<hr/><h3>Crear acceso de trabajador</h3><p>Crea UN SOLO acceso por trabajador. Puedes registrar correo y teléfono al mismo tiempo; ninguno anula al otro. La contraseña inicial se entrega de forma privada.</p><CreateWorkerAccess workers={workers} onCreate={async b=>{try{await adminApi({action:'create',...b});await loadAccessUsers();alert('Acceso único creado correctamente. El trabajador puede entrar con su correo o con su teléfono usando la misma contraseña.')}catch(e){alert(e.message)}}}/><hr/><h3>Cambiar mi contraseña</h3><p>Estando dentro de tu cuenta puedes cambiar tu contraseña sin correo de recuperación.</p><div className="grid"><div className="field"><label>Nueva contraseña</label><input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></div><div className="field"><label>Confirmar contraseña</label><input type="password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></div></div><div className="actions"><button className="primary" onClick={changeOwnPassword}>Guardar nueva contraseña</button></div></section>}

 {tab==='new'&&<section className="card receipt-print"><h2>{editId?'Editar liquidación':'Nueva liquidación'}</h2>
 <div className="grid no-print"><div className="field"><label>Trabajador</label>{isWorker?<input value={workers[0]?.nombre||''} disabled/>:<select value={worker} onChange={e=>chooseWorker(e.target.value)}><option value="">Seleccionar...</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select>}</div>
 <div className="field"><label>Valor hora</label><input type="number" min="0" step=".01" value={rate} onChange={e=>changeHourly(e.target.value)}/><small>Al cambiarlo, Valor día = hora × 8</small></div><div className="field"><label>Valor día (8 horas)</label><input type="number" min="0" step=".01" value={dailyRate} onChange={e=>changeDaily(e.target.value)}/><small>Al cambiarlo, Valor hora = día ÷ 8</small></div>
 <div className="field"><label>Desde</label><input type="date" value={from} onChange={e=>{setFrom(e.target.value);makeRows(e.target.value,to)}}/></div><div className="field"><label>Hasta</label><input type="date" value={to} onChange={e=>{setTo(e.target.value);makeRows(from,e.target.value)}}/></div></div>
 <div className="print-only"><h3>{workers.find(w=>String(w.id)===String(worker))?.nombre}</h3><p><b>Período:</b> {labelDate(from)} — {labelDate(to)} &nbsp; <b>Tarifa:</b> {money(rate)}/h — {money(dailyRate||Number(rate)*8)}/día</p></div>
 {rows.length>0&&<><table><thead><tr><th>Fecha</th><th>Horas</th><th className="money">Valor día</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.fecha}><td>{labelDate(r.fecha)}</td><td><span className="print-only">{r.horas||0}</span><div className="no-print"><input type="number" min="0" step=".25" value={r.horas} onChange={e=>{let a=[...rows];a[i].horas=e.target.value;setRows(a)}}/><button className="quick" onClick={()=>{let a=[...rows];a[i].horas=8;setRows(a)}}>8 h</button></div></td><td className="money">{money(Number(r.horas||0)*Number(rate||0))}</td></tr>)}</tbody></table>
 <div className="grid" style={{marginTop:10}}><div><b>Total horas:</b> {totalHours.toFixed(2)}</div><div className="total">TOTAL: {money(total)}</div></div>
 <div style={{marginTop:14}}><h3>Ajustes adicionales</h3>{adjustments.map((a,i)=><div className="grid" key={i} style={{marginBottom:8}}><div className="field"><select value={a.tipo} onChange={e=>{let x=[...adjustments];x[i].tipo=e.target.value;setAdjustments(x)}}><option value="suma">➕ Sumar</option><option value="resta">➖ Restar</option></select></div><div className="field"><input placeholder="Concepto: bono, adelanto..." value={a.concepto} onChange={e=>{let x=[...adjustments];x[i].concepto=e.target.value;setAdjustments(x)}}/></div><div className="field"><input type="number" min="0" step=".01" placeholder="Valor" value={a.valor} onChange={e=>{let x=[...adjustments];x[i].valor=e.target.value;setAdjustments(x)}}/></div><div className="no-print"><button className="danger" type="button" onClick={()=>setAdjustments(adjustments.filter((_,j)=>j!==i))}>Quitar</button></div></div>)}<div className="actions no-print"><button type="button" onClick={()=>setAdjustments([...adjustments,{tipo:'suma',concepto:'',valor:''}])}>+ Agregar ajuste</button></div>{adjustments.filter(a=>a.concepto).map((a,i)=><p key={i}>{a.tipo==='suma'?'+':'−'} {a.concepto}: {money(a.valor)}</p>)}<div className="total">GRAN TOTAL: {money(grandTotal)}</div></div><div className="grid no-print" style={{marginTop:14}}>{isAdmin&&<><div className="field"><label>Estado</label><select value={status} onChange={e=>{setStatus(e.target.value);if(e.target.value!=='pagado')setMethod('')}}><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select></div>
 {status==='pagado'&&<div className="field"><label>Pagado desde</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Seleccionar...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></div>}
 <div className="field"><label>Observaciones</label><textarea value={obs} onChange={e=>setObs(e.target.value)}/></div></>}{isWorker&&<div className="field"><label>Observaciones</label><textarea value={obs} onChange={e=>setObs(e.target.value)}/></div>}</div>
 <div className="print-only"><p><b>Estado:</b> {status==='pagado'?'Pagado':'Pendiente'} {status==='pagado'&&<> — <b>Pagado desde:</b> {methods.find(m=>String(m.id)===String(method))?.nombre||''}</>}</p>{obs&&<p><b>Observaciones:</b> {obs}</p>}<p>Firma quien paga: ____________________ &nbsp;&nbsp; Firma quien recibe: ____________________</p></div>
 <div className="actions no-print">{isAdmin?<><button className="success" onClick={()=>save('admin')}>{editId?'Guardar cambios':'Guardar liquidación'}</button><button onClick={()=>window.print()}>🖨️ Imprimir</button></>:<><button onClick={()=>save('draft')}>Guardar borrador</button><button className="success" onClick={()=>save('send')}>Enviar al administrador</button></>}{editId&&<button onClick={reset}>Cancelar</button>}</div></>}</section>}

 {isAdmin&&tab==='received'&&<section className="card no-print"><h2>📥 Liquidaciones recibidas</h2><p>Aquí aparecen únicamente las liquidaciones enviadas por los trabajadores y pendientes de decisión.</p>{history.filter(p=>['enviada','en_revision'].includes(p.estado)).length===0?<p><b>No hay liquidaciones pendientes de revisión.</b></p>:<table><thead><tr><th>Trabajador</th><th>Período</th><th>Horas</th><th>Tarifa</th><th>Total enviado</th><th>Acciones</th></tr></thead><tbody>{history.filter(p=>['enviada','en_revision'].includes(p.estado)).map(p=><tr key={p.id}><td><b>{p.trabajadores?.nombre}</b></td><td>{labelDate(p.fecha_desde)} / {labelDate(p.fecha_hasta)}</td><td>{p.total_horas}</td><td>{money(p.valor_hora)}/h<br/><small>{money(p.valor_dia||Number(p.valor_hora||0)*8)}/día</small></td><td><b>{money(p.total_enviado_trabajador??p.gran_total??p.total_pago)}</b></td><td><div className="actions"><button onClick={()=>editPay(p)}>✏️ Editar</button><button onClick={()=>printPay(p)}>🖨️ Ver / Imprimir</button><button className="success" onClick={()=>reviewPay(p,'aprobada')}>✓ Aprobar</button><button onClick={()=>reviewPay(p,'devuelta')}>↩ Devolver</button><button className="danger" onClick={()=>reviewPay(p,'rechazada')}>✕ Rechazar</button></div><textarea className="review-note" placeholder="Comentario para el trabajador (opcional)" value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/>{p.comentario_admin&&<small><b>Nota anterior:</b> {p.comentario_admin}</small>}</td></tr>)}</tbody></table>}</section>}

 {tab==='history'&&<section className="card no-print"><h2>{isAdmin?'Historial y revisión':'Mis liquidaciones'}</h2>{isAdmin&&<div className="field"><label>Filtrar por trabajador</label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select></div>}
 <table><thead><tr><th>Trabajador</th><th>Período</th><th>Horas</th><th>Total</th><th>Estado / Pago</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.trabajadores?.nombre}</td><td>{labelDate(p.fecha_desde)} / {labelDate(p.fecha_hasta)}</td><td>{p.total_horas}</td><td>{money(p.gran_total??p.total_pago)}</td><td>{p.estado||'pendiente'}{p.metodos_pago?.nombre?<><br/><small>{p.metodos_pago.nombre}</small></>:null}</td><td><div className="actions">{isAdmin?<><button onClick={()=>editPay(p)}>Editar</button><button onClick={()=>printPay(p)}>Imprimir</button>{['enviada','en_revision'].includes(p.estado)&&<><button className="success" onClick={()=>reviewPay(p,'aprobada')}>✓ Aprobar</button><button onClick={()=>reviewPay(p,'devuelta')}>↩ Devolver</button><button className="danger" onClick={()=>reviewPay(p,'rechazada')}>✕ Rechazar</button></>}<button onClick={()=>annulPay(p)}>Anular</button><button className="danger" onClick={()=>delPay(p)}>Eliminar</button></>:<>{['borrador','devuelta','pendiente'].includes(p.estado)&&<><button onClick={()=>editPay(p)}>Editar</button><button className="danger" onClick={()=>annulPay(p)}>Anular</button></>}{p.estado==='rechazada'&&<button className="primary" onClick={()=>newFromRejected(p)}>➕ Crear nueva para este período</button>}<button onClick={()=>printPay(p)}>Ver / Imprimir</button></>}</div>{isAdmin&&['enviada','en_revision'].includes(p.estado)&&<textarea className="review-note" placeholder="Comentario para el trabajador (opcional)" value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/>} {p.comentario_admin&&<small><b>Nota admin:</b> {p.comentario_admin}</small>}</td></tr>)}</tbody></table></section>}

 {isAdmin&&tab==='reports'&&<><section className="card no-print"><h2>📊 Informe de pagos</h2><div className="actions"><button onClick={()=>{let t=today();setRFrom(t);setRTo(t);runReport(t,t)}}>Hoy</button></div><div className="grid"><div className="field"><label>Desde</label><input type="date" value={rFrom} onChange={e=>setRFrom(e.target.value)}/></div><div className="field"><label>Hasta</label><input type="date" value={rTo} onChange={e=>setRTo(e.target.value)}/></div></div><div className="actions"><button className="primary" onClick={()=>runReport()}>Generar informe</button>{report.length>0&&<button onClick={()=>window.print()}>🖨️ Imprimir informe</button>}</div>
 {report.length>0&&<><div className="summary"><div className="stat">Liquidaciones<b>{report.length}</b></div><div className="stat">Horas<b>{reportHours.toFixed(2)}</b></div><div className="stat">Total pagado<b>{money(paidTotal)}</b></div></div><p><b>Por forma de pago:</b> {Object.entries(byMethod).map(([k,v])=>`${k}: ${money(v)}`).join(' · ')}</p></>}</section>
 <section className="report-print"><h2>Informe de Pagos</h2><p>Período: {labelDate(rFrom)} — {labelDate(rTo)}</p><div className="summary"><div className="stat">Liquidaciones<b>{report.length}</b></div><div className="stat">Horas<b>{reportHours.toFixed(2)}</b></div><div className="stat">Pagado<b>{money(paidTotal)}</b></div></div>
 <table><thead><tr><th>Trabajador</th><th>Período</th><th>Horas</th><th>Total</th><th>Estado</th><th>Pago</th></tr></thead><tbody>{report.map(p=><tr key={p.id}><td>{p.trabajadores?.nombre}</td><td>{labelDate(p.fecha_desde)}-{labelDate(p.fecha_hasta)}</td><td>{p.total_horas}</td><td>{money(p.gran_total??p.total_pago)}</td><td>{p.estado}</td><td>{p.metodos_pago?.nombre||'-'}</td></tr>)}</tbody></table><p><b>Totales por forma de pago:</b> {Object.entries(byMethod).map(([k,v])=>`${k}: ${money(v)}`).join(' | ')}</p><h3>TOTAL PAGADO: {money(paidTotal)}</h3></section></>}
 </main>
}
function AccessActions({u,workers,onActivate,onWhatsApp,onGmail,onPassword,onDisable}){const [wid,setWid]=useState(u.trabajador_id?String(u.trabajador_id):'');useEffect(()=>setWid(u.trabajador_id?String(u.trabajador_id):''),[u.trabajador_id]);return <div className="actions"><select value={wid} onChange={e=>setWid(e.target.value)}><option value="">Seleccionar trabajador...</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select>{(!u.activo||!u.trabajador_id)&&<button className="primary" disabled={!wid} onClick={()=>onActivate(u,wid)}>✅ Vincular y activar</button>}{u.activo&&u.trabajador_id&&<>{u.telefono&&<button className="primary" onClick={()=>onWhatsApp(u)}>📱 Enviar por WhatsApp</button>}{u.email&&<button className="primary" onClick={()=>onGmail(u)}>✉️ Enviar por Gmail</button>}<button onClick={()=>onPassword(u)}>🔑 Nueva clave temporal</button><button className="danger" onClick={()=>onDisable(u)}>Desactivar</button></>}</div>}

