'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const today=()=>new Date().toLocaleDateString('en-CA')
export default function PaymentManager(){
 const [show,setShow]=useState(false),[rows,setRows]=useState([]),[methods,setMethods]=useState([]),[liq,setLiq]=useState(''),[date,setDate]=useState(today()),[value,setValue]=useState(''),[method,setMethod]=useState(''),[note,setNote]=useState(''),[payments,setPayments]=useState([])
 useEffect(()=>{const check=()=>{const t=document.body?.innerText||'';setShow(t.includes('Informe de pagos')||t.includes('Informe de Pagos'))};check();const o=new MutationObserver(check);o.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>o.disconnect()},[])
 async function load(){const [{data:r},{data:m},{data:p}]=await Promise.all([sb.from('v_informe_liquidaciones_detallado').select('*').gt('saldo_pendiente',0).order('fecha_desde',{ascending:false}),sb.from('metodos_pago').select('id,nombre').eq('activo',true).order('nombre'),sb.from('pagos_liquidacion').select('*, liquidaciones(trabajador_id,fecha_desde,fecha_hasta,trabajadores(nombre)), metodos_pago(nombre)').order('fecha',{ascending:false}).limit(50)]);setRows(r||[]);setMethods(m||[]);setPayments(p||[])}
 useEffect(()=>{if(show)load()},[show])
 const selected=rows.find(x=>String(x.id)===liq)
 async function save(){if(!liq)return alert('Selecciona una liquidación');const v=Number(value);if(!v||v<=0)return alert('Escribe un valor de pago válido');if(v>Number(selected?.saldo_pendiente||0)+.001)return alert(`El pago no puede superar el saldo por pagar de ${money(selected?.saldo_pendiente)}`);const {error}=await sb.from('pagos_liquidacion').insert({liquidacion_id:Number(liq),fecha:date,valor:v,metodo_pago_id:method?Number(method):null,concepto:note||'Pago / abono'});if(error)return alert(error.message);setValue('');setNote('');await load();alert('Pago / abono registrado correctamente')}
 async function remove(p){if(!confirm(`¿Eliminar el pago de ${money(p.valor)}?`))return;const {error}=await sb.from('pagos_liquidacion').delete().eq('id',p.id);if(error)return alert(error.message);await load()}
 if(!show)return null
 return <div style={{maxWidth:1200,margin:'14px auto',padding:'0 4px'}}><section className="card no-print"><h2>💵 Pagos y abonos</h2><p>Registra aquí el dinero realmente entregado al trabajador. Un pago reduce el <b>Saldo por pagar</b>, pero no modifica el valor causado ni el estado administrativo de la liquidación.</p>
 <div className="grid"><div className="field"><label>Liquidación</label><select value={liq} onChange={e=>setLiq(e.target.value)}><option value="">Seleccionar...</option>{rows.map(x=><option key={x.id} value={x.id}>{x.trabajador} · {x.fecha_desde} a {x.fecha_hasta} · Saldo {money(x.saldo_pendiente)}</option>)}</select></div><div className="field"><label>Fecha del pago</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Valor pagado</label><input type="number" min="0.01" step=".01" value={value} onChange={e=>setValue(e.target.value)}/></div><div className="field"><label>Forma de pago</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Sin especificar</option>{methods.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></div><div className="field"><label>Concepto / observación</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej. Abono semanal"/></div></div>
 {selected&&<p><b>{selected.trabajador}</b> — Total liquidado: <b>{money(selected.total_liquidado)}</b> · Pagado: <b>{money(selected.total_pagado)}</b> · Saldo por pagar: <b>{money(selected.saldo_pendiente)}</b></p>}
 <div className="actions"><button className="primary" onClick={save}>💵 Registrar pago / abono</button></div>
 <h3>Últimos pagos registrados</h3>{payments.length===0?<p>No hay pagos registrados.</p>:<div style={{overflowX:'auto'}}><table><thead><tr><th>Fecha</th><th>Trabajador</th><th>Período</th><th>Valor</th><th>Forma de pago</th><th>Concepto</th><th></th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.fecha}</td><td>{p.liquidaciones?.trabajadores?.nombre||'-'}</td><td>{p.liquidaciones?.fecha_desde} - {p.liquidaciones?.fecha_hasta}</td><td>{money(p.valor)}</td><td>{p.metodos_pago?.nombre||'-'}</td><td>{p.concepto||'-'}</td><td><button className="danger" onClick={()=>remove(p)}>Eliminar</button></td></tr>)}</tbody></table></div>}
 </section></div>
}
