'use client'
import {useEffect} from 'react'

export default function PdfHalfLetterButton(){
 function findReceipt(){const candidates=[...document.querySelectorAll('.receipt-print')];return candidates.find(r=>r.querySelector('tbody tr'))||candidates[0]||null}
 useEffect(()=>{const onClick=e=>{const b=e.target?.closest?.('button');if(!b)return;const text=(b.textContent||'').trim().toLowerCase();if(text.includes('imprimir informe'))return;if(text==='imprimir'||text.includes('ver / imprimir')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();setTimeout(()=>makePdf(),220)}};document.addEventListener('click',onClick,true);return()=>document.removeEventListener('click',onClick,true)},[])
 function getBody(){const r=findReceipt();if(!r)return null;const worker=(r.querySelector('.print-only h3')?.textContent||r.querySelector('h2,h3')?.textContent||'').trim();const period=(r.querySelector('.print-only p')?.textContent||[...r.querySelectorAll('p')].find(x=>/per[ií]odo/i.test(x.textContent||''))?.textContent||'').trim();const rows=[...r.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(td=>(td.innerText||'').trim().split('\n')[0])).filter(x=>x.length>=3);const totals=[...r.querySelectorAll('.total')].map(x=>(x.textContent||'').trim());const adjustTitle=[...r.querySelectorAll('h3')].find(x=>(x.textContent||'').trim()==='Ajustes adicionales'),adjustBox=adjustTitle?.parentElement;let adjustments=adjustBox?[...adjustBox.querySelectorAll(':scope > p')].map(x=>(x.textContent||'').trim()).filter(Boolean):[];const paymentLines=[...r.querySelectorAll('[data-print-payment]')].map(x=>x.getAttribute('data-print-payment')).filter(Boolean);adjustments=[...adjustments,...paymentLines];const printBlocks=[...r.querySelectorAll('.print-only')],footer=printBlocks.length?(printBlocks[printBlocks.length-1].innerText||'').trim():'';const allText=r.innerText||'';return {worker,period,rows,totalHours:(allText.match(/Total horas:\s*[\d.]+/i)||[''])[0],total:totals.find(x=>/^TOTAL:/i.test(x))||((allText.match(/TOTAL:\s*\$[\d,.]+/i)||[''])[0]),adjustments,grandTotal:totals.find(x=>/GRAN TOTAL:/i.test(x))||((allText.match(/GRAN TOTAL:\s*\$[\d,.]+/i)||[''])[0]),footer}}
 async function makePdf(){let body=null;for(let i=0;i<8&&!body;i++){body=getBody();if(!body)await new Promise(r=>setTimeout(r,150))}if(!body)return alert('No se pudo preparar la liquidación para imprimir. Intenta nuevamente.');const res=await fetch('/api/pdf-media-carta',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!res.ok)return alert('No fue posible generar el PDF media carta.');const blob=await res.blob(),url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}
 return null
}
