'use client'
import {useEffect} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))

export default function PdfHalfLetterButton(){
 function findReceipt(){const candidates=[...document.querySelectorAll('.receipt-print')];return candidates.find(r=>r.querySelector('tbody tr'))||candidates[0]||null}
 useEffect(()=>{const nativePrint=window.print.bind(window);let reportPrint=false;const onClick=e=>{const b=e.target?.closest?.('button');if(!b)return;reportPrint=(b.textContent||'').trim().toLowerCase().includes('imprimir informe')};const unifiedPrint=()=>{if(reportPrint){reportPrint=false;return nativePrint()}setTimeout(()=>makePdf(),320)};document.addEventListener('click',onClick,true);window.print=unifiedPrint;return()=>{document.removeEventListener('click',onClick,true);window.print=nativePrint}},[])
 function getBody(){const r=findReceipt();if(!r)return null;const worker=(r.querySelector('.print-only h3')?.textContent||r.querySelector('h2,h3')?.textContent||'').trim();const period=(r.querySelector('.print-only p')?.textContent||[...r.querySelectorAll('p')].find(x=>/per[ií]odo/i.test(x.textContent||''))?.textContent||'').trim();const rows=[...r.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(td=>(td.innerText||'').trim().split('\n')[0])).filter(x=>x.length>=3);const totals=[...r.querySelectorAll('.total')].map(x=>(x.textContent||'').trim());const adjustTitle=[...r.querySelectorAll('h3')].find(x=>(x.textContent||'').trim()==='Ajustes adicionales'),adjustBox=adjustTitle?.parentElement;let adjustments=adjustBox?[...adjustBox.querySelectorAll(':scope > p')].map(x=>(x.textContent||'').trim()).filter(Boolean):[];const paymentLines=[...r.querySelectorAll('[data-print-payment]')].map(x=>x.getAttribute('data-print-payment')).filter(Boolean);adjustments=[...adjustments,...paymentLines];const printBlocks=[...r.querySelectorAll('.print-only')],footer=printBlocks.length?(printBlocks[printBlocks.length-1].innerText||'').trim():'';const allText=r.innerText||'';const sel=r.querySelector('select'),dates=[...r.querySelectorAll('input[type=date]')].map(x=>x.value).filter(Boolean);return {worker,period,rows,totalHours:(allText.match(/Total horas:\s*[\d.]+/i)||[''])[0],total:totals.find(x=>/^TOTAL:/i.test(x))||((allText.match(/TOTAL:\s*\$[\d,.]+/i)||[''])[0]),adjustments,grandTotal:(allText.match(/GRAN TOTAL:\s*\$[\d,.]+/i)||[''])[0]||(totals.find(x=>/GRAN TOTAL:/i.test(x))||''),footer,workerId:sel?.value||'',from:dates[0]||'',to:dates[1]||''}}
 async function enrichPayments(body){if(!body.workerId||!body.from||!body.to)return body;const {data:l}=await sb.from('liquidaciones').select('id,total_pago,gran_total').eq('trabajador_id',Number(body.workerId)).eq('fecha_desde',body.from).eq('fecha_hasta',body.to).maybeSingle();if(!l)return body;const {data:p}=await sb.from('pagos_liquidacion').select('valor,concepto,metodos_pago(nombre)').eq('liquidacion_id',l.id).order('fecha');if(!p?.length)return body;const existing=body.adjustments.join(' ').toLowerCase();const payLines=p.filter(x=>!existing.includes(String(Number(x.valor)).toLowerCase())).map(x=>`Abono: ${money(x.valor)} (${x.concepto||'Abono'}) · ${x.metodos_pago?.nombre||'Sin forma de pago'}`);body.adjustments=[...body.adjustments,...payLines];const paid=p.reduce((s,x)=>s+Number(x.valor||0),0);const caused=Number(l.gran_total??l.total_pago??0);body.grandTotal=`GRAN TOTAL: ${money(Math.max(caused-paid,0))}`;return body}
 async function makePdf(){let body=null;for(let i=0;i<14;i++){body=getBody();if(body?.rows?.length&&body?.worker)break;await new Promise(r=>setTimeout(r,150))}if(!body?.rows?.length)return alert('No se pudo preparar la liquidación para imprimir. Intenta nuevamente.');body=await enrichPayments(body);const res=await fetch('/api/pdf-media-carta',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!res.ok)return alert('No fue posible generar el PDF media carta.');const blob=await res.blob(),url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}
 return null
}
