import {createClient} from '@supabase/supabase-js'
import {NextResponse} from 'next/server'
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY
function adminClient(){return createClient(url,secret,{auth:{autoRefreshToken:false,persistSession:false}})}
async function authorize(req){
 const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null
 const a=adminClient();const {data:{user}}=await a.auth.getUser(token);if(!user)return null
 const {data:p}=await a.from('usuarios_app').select('rol,activo').eq('user_id',user.id).single();return p?.rol==='administrador'&&p?.activo?{a,user}:null
}
export async function POST(req){
 try{const auth=await authorize(req);if(!auth)return NextResponse.json({error:'No autorizado'},{status:401});const b=await req.json();
  if(b.action==='create'){if(!b.login||!b.password||b.password.length<8||!b.trabajador_id)return NextResponse.json({error:'Acceso, trabajador y contraseña de mínimo 8 caracteres son obligatorios'},{status:400});const isPhone=b.login_type==='phone';const login=String(b.login).trim();if(isPhone&&!/^\+1\d{10}$/.test(login))return NextResponse.json({error:'Teléfono inválido. Usa +1 seguido de 10 dígitos'},{status:400});const attrs=isPhone?{phone:login,password:b.password,phone_confirm:true}:{email:login,password:b.password,email_confirm:true};const {data,error}=await auth.a.auth.admin.createUser(attrs);if(error)throw error;const {error:pe}=await auth.a.from('usuarios_app').upsert({user_id:data.user.id,email:data.user.email||null,telefono:data.user.phone||null,trabajador_id:Number(b.trabajador_id),rol:'trabajador',activo:true,requiere_cambio_clave:true});if(pe)throw pe;return NextResponse.json({ok:true,user_id:data.user.id,requiere_cambio_clave:true})}
  if(b.action==='unify'){if(!b.primary_user_id||!b.secondary_user_id||b.primary_user_id===b.secondary_user_id)return NextResponse.json({error:'Selecciona dos accesos diferentes'},{status:400});const {data:primary}=await auth.a.auth.admin.getUserById(b.primary_user_id);const {data:secondary}=await auth.a.auth.admin.getUserById(b.secondary_user_id);if(!primary?.user||!secondary?.user)return NextResponse.json({error:'No se encontraron ambos accesos'},{status:404});const {data:pp}=await auth.a.from('usuarios_app').select('*').eq('user_id',b.primary_user_id).single();const {data:sp}=await auth.a.from('usuarios_app').select('*').eq('user_id',b.secondary_user_id).single();const workerId=Number(b.trabajador_id||pp?.trabajador_id||sp?.trabajador_id);if(!workerId)return NextResponse.json({error:'No hay trabajador para unificar'},{status:400});const email=primary.user.email||secondary.user.email||pp?.email||sp?.email||null;const phone=primary.user.phone||secondary.user.phone||pp?.telefono||sp?.telefono||null;const upd={};if(email&&!primary.user.email)upd.email=email;if(phone&&!primary.user.phone)upd.phone=phone;if(Object.keys(upd).length){upd.email_confirm=!!upd.email;upd.phone_confirm=!!upd.phone;const {error:ue}=await auth.a.auth.admin.updateUserById(b.primary_user_id,upd);if(ue)throw ue}await auth.a.from('usuarios_app').update({trabajador_id:workerId,rol:'trabajador',activo:true,email:email,telefono:phone}).eq('user_id',b.primary_user_id);await auth.a.from('usuarios_app').update({trabajador_id:null,activo:false}).eq('user_id',b.secondary_user_id);if(email)await auth.a.from('usuario_accesos').upsert({user_id:b.primary_user_id,tipo:'email',valor:String(email).toLowerCase()},{onConflict:'tipo,valor'});if(phone)await auth.a.from('usuario_accesos').upsert({user_id:b.primary_user_id,tipo:'telefono',valor:String(phone).replace(/[^0-9+]/g,'')},{onConflict:'tipo,valor'});return NextResponse.json({ok:true,email,phone})}
  if(b.action==='password'){if(!b.user_id||!b.password||b.password.length<8)return NextResponse.json({error:'Contraseña de mínimo 8 caracteres requerida'},{status:400});const {data:p}=await auth.a.from('usuarios_app').select('rol').eq('user_id',b.user_id).single();if(p?.rol==='administrador'&&b.user_id!==auth.user.id)return NextResponse.json({error:'No puedes cambiar la contraseña de otro administrador'},{status:403});const {error}=await auth.a.auth.admin.updateUserById(b.user_id,{password:b.password});if(error)throw error;if(p?.rol==='trabajador'){const {error:pe}=await auth.a.from('usuarios_app').update({requiere_cambio_clave:true}).eq('user_id',b.user_id);if(pe)throw pe}return NextResponse.json({ok:true})}
  return NextResponse.json({error:'Acción no válida'},{status:400})
 }catch(e){return NextResponse.json({error:e.message||'Error del servidor'},{status:500})}
}
